name = "tanstack"
main = "dist/server/server.js"

compatibility_date = "2025-11-15"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "dist/client"
binding = "ASSETS"

[observability]
enabled = true