name = "tanstack"
main = "dist/server/server.js"

[assets]
directory = "dist/client"
binding = "ASSETS"  # optional but recommended

compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[observability]
enabled = true