name = "tanstack"
main = "dist/server/server.js"
assets = ["dist/client","dist/assets/"]
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[observability]
enabled = true